- hosts: '{{ server | default("hadoop_client") }}'
  roles:
    - { role: common, common_config_hostname: True }
    - openjdk
    - scala
    - sbt
    - activator_mini
    - git
    - maven
    - spark_comm
