---
- name: check_hadoop_group_exists
  shell: grep -e "^hadoop" /etc/group
  register: check_hadoop_group

- name: add_spark_user_with_hadoop_group
  user: name=spark groups=hadoop
  when: check_hadoop_group.rc == 0

- name: add_spark_user_without_hadoop_group
  user: name=spark
  when: check_hadoop_group.rc != 0

# vim: et ts=2 sw=2
