- hosts: "{{ server | default('endo_dashboard') }}"
  roles:
    - { role: common, common_config_hostname: True }
    - common
    - epel
    - postgresql
    - openjdk
    - endosnipe_datacollector

