# ========================
# role-wide parameters
# ========================
cdh5_data_dir_list:
  - '/data'
  - '/data/1'

# =========================================
# parameters for each configuration file
# =========================================
# core-site.xml.j2
cdh5_fs_defaultFS: 'hdfs://mycluster'

# hdfs-site.xml.j2
cdh5_dfs_nameservices: 'mycluster'
cdh5_dfs_nn_name_dir_list:
  - '/data/1/dfs/nn'
cdh5_dfs_dn_data_dir_list:
  - '/data/1/dfs/dn'
cdh5_dfs_journalnode_edits_dir: '/data/1/dfs/jn'
cdh5_fencing_methods: 'shell(/bin/true)'
# cdh5_fencing_private_key: '/home/centos/mykey.pem'

# mapred-site.xml.j2
cdh5_mr_mapreduce_task_tmp_dir: '/tmp/mapred/${user.name}'

# yarn-site.xml.j2
cdh5_yarn_nm_local_dirs_list:
  - '/data/1/yarn/local'
cdh5_yarn_nm_log_dirs_list:
  - '/data/1/yarn/logs'
cdh5_yarn_nm_remote_app_log_dir: '/var/log/hadoop-yarn/apps'
cdh5_yarn_nodemanager_resource_cpu_vcores: '8'
cdh5_yarn_scheduler_minimum_allocation_vcores: '1'
cdh5_yarn_scheduler_maximum_allocation_vcores: '8'
cdh5_yarn_nodemanager_resource_memory_mb: '2048'
cdh5_yarn_scheduler_minimum_allocation_mb: '512'
cdh5_yarn_scheduler_maximum_allocation_mb: '2024'
cdh5_yarn_nodemanager_vmem_pmem_ratio: '1.2'
cdh5_yarn_nodemanager_pmem_check_enabled: 'true'
cdh5_yarn_nodemanager_vmem_check_enabled: 'true'
cdh5_yarn_rm_cluster_id: 'yarn-cluster'
cdh5_yarn_rm_connect_retry_interval_ms: '2000'
cdh5_yarn_arn_app_mapreduce_am_scheduler_connection_wait_interval_ms: '5000'

# hadoop-metrics2.properties
cdh5_ganglia_servers: '239.2.11.71:8649'
