- hosts: hadoop_resourcemanager
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-yarn-resourcemanager 

- hosts: hadoop_client
  tasks:
    - name: wait_for_resourcemanager_web_service_port
      wait_for: host={{ item }} port=8088 timeout={{ cdh5_wait_for_timeout }}
      with_items: "{{ groups['hadoop_resourcemanager'] }}"

- hosts: hadoop_slave
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-yarn-nodemanager

- hosts: hadoop_client
  tasks:
    - name: wait_for_nodemanager_service_port
      wait_for: host={{ item }} port=8040 timeout={{ cdh5_wait_for_timeout }}
      with_items: "{{ groups['hadoop_slave'] }}"

- hosts: hadoop_other
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-mapreduce-historyserver

- hosts: hadoop_client
  tasks:
    - name: wait_for_other_service_port
      wait_for: host={{ item }} port=19888 timeout={{ cdh5_wait_for_timeout }}
      with_items: "{{ groups['hadoop_other'] }}"
