- hosts: hadoop_zookeeperserver
  gather_facts: no
  tasks:
    - name: stop_daemons
      service: name={{ item }} state=stopped
      with_items:
        - zookeeper-server

- hosts: hadoop_client
  tasks:
    - name: wait_for_zookeeper_service_port_close
      wait_for: host={{ item }} port=2181 state=stopped timeout={{ cdh5_wait_for_timeout }}
      with_items: groups['hadoop_zookeeperserver']
