- name: copy_gmetad.conf
  template: src=gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf
  notify:
    - restart_gmetad

- name: copy_ganglia.conf
  template: src=ganglia.conf.j2 dest=/etc/httpd/conf.d/ganglia.conf
  notify:
    - restart_gmetad

# vim: et ts=2 sw=2
