---
# tasks file for roles/heapstats

- include: centos6.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- include: centos6.yml
  when: ansible_distribution == "Amazon"

- include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
