- name: copy_spark-defaults.conf
  template: src={{ spark_comm_defaults_tmpl }} dest=/etc/spark/conf/spark-defaults.conf

- name: copy_spark-env.sh
  template: src={{ spark_comm_env_tmpl }} dest=/etc/spark/conf/spark-env.sh

- name: copy_metrics.properties
  template: src={{ spark_comm_metrics_tmpl }} dest=/etc/spark/conf/metrics.properties

- name: copy_log4j_spark_properties
  template: src={{ spark_comm_log4j_spark_properties_tmpl }} dest=/etc/spark/conf/log4j-spark.properties

- name: copy_profile_of_spark
  template: src=spark.sh.j2 dest=/etc/profile.d/spark.sh

- name: copy_hive-site.xml
  template: src={{ spark_comm_hive_site_tmpl }} dest=/etc/spark/conf/hive-site.xml
