- name: make_spark_directory
  file: path={{ spark_comm_dir }} owner=spark group=spark state=directory

- name: get_spark_package
  get_url: url={{ spark_comm_package_url_base }}/{{ spark_comm_package_name }}.tgz dest=/usr/local/spark/{{ spark_comm_package_name }}.tgz

- name: unarchive_package
  shell: tar xvzf {{ spark_comm_package_name }}.tgz chdir=/usr/local/spark creates=/usr/local/spark/{{ spark_comm_package_name }}/LICENSE

- name: configure_owner_and_group_of_unarhived_package
  file: path=/usr/local/spark/{{ spark_comm_package_name }} owner=spark group=spark recurse=yes

- name: make_alternatives_entry_of_spark_default
  alternatives: name=spark_package_default path=/usr/local/spark/{{ spark_comm_package_name }} link=/usr/local/spark/default

- name: make_etc_spark_dir
  file: path=/etc/spark owner=spark group=spark state=directory

- name: make_alternatives_entry_of_spark_conf
  alternatives: name=spark-conf path=/usr/local/spark/default/conf link=/etc/spark/conf

- name: make_log_dir
  file: path=/var/log/spark state=directory owner=spark group=spark

- name: make_alternatives_entry_of_spark_log
  alternatives: name=spark_log path=/var/log/spark link=/usr/local/spark/default/logs
