- hosts: '{{ server | default("localhost") }}'
  vars:
    ambari_server: "localhost:8080"
    ambari_user: "admin"
    ambari_passwd: "admin"
    ambari_cluster_name: "localhost"
  tasks:
    - name: stop_zookeeper
      uri:
        url: "http://{{ ambari_server }}/api/v1/clusters/{{ ambari_cluster_name }}/services/ZOOKEEPER"
        user: "{{ ambari_user }}"
        password: "{{ ambari_passwd }}"
        HEADER_X-Requested-By: "ambari"
        method: PUT
        body: '{ "RequestInfo" : { "context" : "Stop ZOOKEEPER via REST" }, "Body" : { "ServiceInfo" : { "state" : "INSTALLED" } } }'
        force_basic_auth: yes
      register: command_result
      failed_when: command_result.status not in [202, 200]
      changed_when: command_result.status == 202

    - debug: msg={{ command_result.content.split('\\n') }}
      when: command_result.status != 200

    - name: check_port
      wait_for:
        host: "{{ item }}"
        port: "{{ ambari_zk_port }}"
        timeout: "{{ ambari_timeout }}"
        state: stopped
      with_items: "{{ ambari_zk_servers }}"
      




