- name: mkdir_/usr/local/kafka
  file: path=/usr/local/kafka owner=kafka group=kafka state=directory

- name: download_kafka_packages
  get_url: url=http://ftp.riken.jp/net/apache/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz dest=/usr/local/kafka/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz

- name: unarchive_kafka_packages
  shell: tar xvzf kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz chdir=/usr/local/kafka creates=/usr/local/kafka/default/LICENSE

- name: chown_of_kafka_packages
  file: path=/usr/local/kafka/kafka_{{ kafka_scala_version }}-{{ kafka_version }} recurse=yes owner=kafka group=kafka state=directory

- name: make_alternatives_link_of_kafka_package
  alternatives: name=kafka_package path=/usr/local/kafka/kafka_{{ kafka_scala_version }}-{{ kafka_version }} link=/usr/local/kafka/default

- name: mkdir_/etc/kafka
  file: path=/etc/kafka state=directory owner=kafka group=kafka

- name: make_alternatives_link_of_kafka_config
  alternatives: name=kafka_config path=/usr/local/kafka/default/config link=/etc/kafka/conf
