- hosts: "{{ server | default('hadoop_pseudo') }}"
  gather_facts: no
  become: True
  become_user: hdfs
  tasks:
    - name: remove_tmp_dir
      shell: hdfs dfs -rm -r /tmp
      ignore_errors: True

    - name: make_intermediate_dir
      shell: hdfs dfs -mkdir -p /tmp/hadoop-yarn/staging/history/done_intermediate

    - name: chown_intermediate_dir
      shell: hdfs dfs -chown -R mapred:mapred /tmp/hadoop-yarn/staging

    - name: chmod_tmp_dir
      shell: hdfs dfs -chmod -R 1777 /tmp 

    - name: make_log_dir
      shell: hdfs dfs -mkdir -p /var/log/hadoop-yarn

    - name: chown_log_dir
      shell: hdfs dfs -chown yarn:hadoop /var/log/hadoop-yarn

    - name: make_log_dir_for_spark
      shell: hdfs dfs -mkdir -p /var/log/spark

    - name: chown_log_dir_for_spark
      shell: hdfs dfs -chown spark:hadoop /var/log/spark

    - name: chown_log_dir
      shell: hdfs dfs -chmod 777 /var/log/spark
