- hosts: "{{ server | default('hadoop_pseudo') }}"
  gather_facts: no
  become: True
  become_user: hdfs
  tasks:
    - name: format_hdfs
      shell: yes | hdfs namenode -format

- hosts: "{{ server | default('hadoop_pseudo') }}"
  gather_facts: no
  tasks:
    - name: start_namenode
      service: name=hadoop-hdfs-namenode state=started
