- name: copy_server.properties
  template: src=server.properties.j2 dest=/etc/kafka/server.properties

- name: copy_connect-standalone.properties
  template: src=connect-standalone.properties.j2 dest=/etc/kafka/connect-standalone.properties

- name: copy_connect-distributed.properties
  template: src=connect-distributed.properties.j2 dest=/etc/kafka/connect-distributed.properties

- name: mkdir_/var/lib/kafka
  file: path=/var/lib/kafka owner=kafka group=kafka state=directory

- name: chown_/var/log/kafka
  file: path=/var/log/kafka owner=kafka group=kafka state=directory

- name: copy_supervisor_configs
  template: src={{ item }}.ini.j2 dest=/etc/supervisord.d/{{ item }}.ini
  with_items:
    - kafka-server
    - kafka-connect
  notify: restart_supervisord
