- name: insert_section_to_supervisord.conf
  blockinfile:
    dest: /etc/supervisord.conf
    marker: '; {mark} ANSIBLE MANAGED BLOCK'
    block: |
      [program:kafka-server]
      command=/usr/local/confluent_kafka/default/bin/kafka-server-start /etc/confluent/kafka/server.properties
      user=kafka
      autorestart=false
      autostart=false
      stdout_logfile=/var/log/confluent/kafka/kafka-server.log
      stdout_logfile_maxbytes=100MB
      stdout_logfile_backups=5
      stdout_capture_maxbytes=100MB
      redirect_stderr=true
      
      [program:schema-registry]
      command=/usr/local/confluent_kafka/default/bin/schema-registry-start /etc/confluent/schema-registry/schema-registry.properties
      user=kafka
      autorestart=true
      autostart=false
      stdout_logfile=/usr/local/confluent_kafka/default/logs/schema-registry.log
      stdout_logfile_maxbytes=100MB
      stdout_logfile_backups=5
      stdout_capture_maxbytes=100MB
      redirect_stderr=true
      
      [program:kafka-rest]
      command=/usr/local/confluent_kafka/default/bin/kafka-rest-start /etc/confluent/kafka-rest/kafka-rest.properties
      user=kafka
      autorestart=true
      autostart=false
      stdout_logfile=/usr/local/confluent_kafka/default/logs/kafka-rest.log
      stdout_logfile_maxbytes=100MB
      stdout_logfile_backups=5
      stdout_capture_maxbytes=100MB
      redirect_stderr=true
