- hosts: "{{ server | default('confluent_kafka_connect') }}"
  sudo: yes
  tasks:
    - name: start_kafka_connect
      shell: supervisorctl start kafka-connect
    - name: verify_port
      wait_for: host=localhost port=8083 state=started timeout={{ confluent_kafka_wait_for_timeout }}
