- hosts: "{{ server | default('confluent_kafka_connect') }}"
  sudo: yes
  tasks:
    - name: stop_kafka_connect
      shell: supervisorctl stop kafka-connect
    - name: verify_port
      wait_for: host=localhost port=8083 state=stopped timeout={{ confluent_kafka_wait_for_timeout }}
