---
# defaults file for roles/confluent_kafka

confluent_scala_version: '2.11.7'
confluent_kafka_num_partitions: 3
confluent_kafka_log_dirs: '/var/lib/kafka'
confluent_kafka_zookeeper_connect: '{{ groups["hadoop_zookeeperserver"] | join(":2181,") }}:2181'
#confluent_kafka_rest_id: 'kafka-rest-test-serve'
#confluent_schema_registry: '{{ groups["confluent_schema_registry"][0] }}:8081'

# The following parameters should be configured in group variables or inventory files
# confluent_kafka_broker_id:
