---
# defaults file for roles/alluxio_conf
#
# alluxio-site.properties
alluxio_yarn_master: "{{ groups['hadoop_slave'][0] }}"
alluxio_yarn_hdfs_uri: "hdfs://mycluster"
alluxio_yarn_underfs_addr: "{{ alluxio_yarn_hdfs_uri }}/tmp/underFSStorage"
alluxio_yarn_auth_permission_enabled: "false"
alluxio_yarn_worker_mem: "1GB"
