- hosts: "{{ server | default('endo_dashboard') }}"
  tasks:
    - name: postgresql_initdb
      shell: /sbin/service postgresql initdb

    - name: start postgresql
      service: name=postgresql state=started  enabled=yes

