---
# tasks file for roles/jenkins

# Installation
- name: download_repo_file
  get_url: url=https://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo 
  tags: jenkins

- name: import_key
  shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  tags: jenkins

- name: yum_install_jenkins
  yum: name=jenkins state=installed
  tags: jenkins

# Configuration
- name: copy_config
  template: src=jenkins.j2 dest=/etc/sysconfig/jenkins
  notify: restart_jenkins
  tags: jenkins

- name: mkdir_/var/lib/jenkins/.ssl
  file: path=/var/lib/jenkins/.ssl state=directory owner=jenkins group=jenkins
  tags: jenkins

- name: create_keystore
  shell: keytool -noprompt -dname "CN=example.com, OU=example, O=exmaple, L=example, S=examle, C=example" -genkey -alias jenkins-ssl-cert -keyalg RSA -keystore .ssl/.keystore -validity 365 -storepass jenkinspass -keypass jenkinspass chdir=/var/lib/jenkins creates=/var/lib/jenkins/.ssl/.keystore
  notify: restart_jenkins
  tags: jenkins

- name: chown_/var/lib/jenkins/.ssl
  file: path=/var/lib/jenkins/.ssl state=directory owner=jenkins group=jenkins recurse=yes
  notify: restart_jenkins
  tags: jenkins

- name: deploy_jenkins.conf
  template: src=jenkins.conf.j2 dest=/etc/httpd/conf.d/jenkins.conf
  notify: restart_httpd
  tags: jenkins

# Service
- name: enable_service
  service: name=jenkins state=started enabled=yes
  tags: jenkins
