---
# defaults file for roles/td-agent

#td_agent_plugins:
#  - fluent-plugin-webhdfs

td_agent_source_defines:
  - |
    <source>
      type forward
    </source>
  - |
    <source>
      type http
      port 8888
    </source>

td_agent_match_defines:
  - |
    <match debug.**>
      type stdout
    </match>
