---
# tasks file for roles/tomcat
- name: install_tomcat
  yum: name={{ item }} state=installed
  with_items:
    - tomcat
    - tomcat-admin-webapps
  tags: tomcat

- name: deploy_server.xml
  template: src=server.xml.j2 dest=/etc/tomcat/server.xml
  tags: tomcat
