# transparent huge pages
- name: deploy_transparent_hugepages_configs
  template: src=rc.local.j2 dest=/etc/rc.d/rc.local mode=755 owner=root group=root

- name: set_transparent_hugepages
  shell: echo never > /sys/kernel/mm/transparent_hugepage/{{ item }}
  with_items:
    - enabled
    - defrag

# tuned for CentOS7
- name: create_tuned_directory
  file: path=/usr/lib/tuned/common state=directory mode=755 owner=root group=root
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: configure_tuned_hadoop-base
  template: src=tuned.conf.j2 dest=/usr/lib/tuned/common/tuned.conf mode=644 owner=root group=root
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: set_tuned_to_common
  shell: /sbin/tuned-adm profile common
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# misc
- name: copy_limits_conf
  template: src=limits.conf.j2 dest=/etc/security/limits.conf mode=644 owner=root group=root

- name: copy_hosts
  copy: src={{ common_hosts_tmpl }} dest=/etc/hosts
  when: common_hosts_replace and ansible_virtualization_type != 'docker'

- name: set_hostname_to_inventory_hostname
  hostname: name={{ inventory_hostname }}
  when: common_config_hostname

- name: no_requiretty_for_root_and_wheel
  template: src={{ item }} dest=/etc/sudoers.d/{{ item }}
  with_items:
    - root
    - wheel

- name: copy_sudoers
  template: src=sudoers.j2 dest=/etc/sudoers

- name: copy_lang.sh
  template: src=lang.sh.j2 dest=/etc/profile.d/lang.sh

- name: set_timezone_for_centos7
  shell: timedatectl set-timezone {{ common_timezone }}
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: deploy_journald_configuration
  template: src=journald.conf.j2 dest=/etc/systemd/journald.conf mode=755 owner=root group=root
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  notify:
    - restart_journald
