# install
- include: install.yml tags=install,common

# selinux
- include: selinux.yml tags=selinux,common
  when: ansible_virtualization_type != 'docker'

# config
- include: config.yml tags=config,common

# service
- include: service_centos6.yml tags=service,common
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' and ansible_virtualization_type != 'docker'

- include: service_centos7.yml tags=service,common
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' and ansible_virtualization_type != 'docker'

- include: service.yml tags=service,common
