- hosts: "{{ server | default('hadoop_all') }}"
  tasks:
    - name: stop_gmond
      service: name=gmond state=stopped

- hosts: "{{ server | default('hadoop_other') }}"
  tasks:
    - name: stop_httpd
      service: name=httpd state=stopped
    - name: stop_gmetad
      service: name=gmetad state=stopped
