- name: chown_/var/log/kafka
  file: path=/var/log/kafka owner=kafka group=kafka state=directory

- name: copy_kafka-rest.properties
  template: src=kafka-rest.properties.j2 dest=/etc/kafka-rest/kafka-rest.properties

- name: copy_supervisor_configs
  template: src=kafka-rest.ini.j2 dest=/etc/supervisord.d/kafka-rest.ini
  notify: restart_supervisord
