- name: check_jdk_installed
  shell: rpm -qa|grep jdk-{{ jdk_version }}
  ignore_errors: yes
  register: check_jdk_installed

- name: download_oraclejdk_by_wget
  shell: >
         wget --no-check-certificate --no-cookies - --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version }}-{{ jdk_hotspot }}/jdk-{{ jdk_version }}-linux-x64.rpm -O jdk-{{ jdk_version }}-linux-x64.rpm chdir={{ jdk_tmppath }} creates={{ jdk_tmppath }}/jdk-{{ jdk_version }}-linux-x64.rpm
  when: check_jdk_installed.rc != 0
  ignore_errors: True

- name: md5sum_rpm
  shell: md5sum /tmp/jdk-{{ jdk_version }}-linux-x64.rpm
  register: md5sum_of_jdk

- name: check_md5sum
  fail: msg="md5sum does not match ... {{ md5sum_of_jdk.stdout }} should be {{ jdk_md5sum }}"
  when:  md5sum_of_jdk.stdout.find('{{ jdk_md5sum }}')

- name: install_oraclejdk
  yum: name=/tmp/jdk-{{ jdk_version }}-linux-x64.rpm state=installed
  when: check_jdk_installed.rc != 0
