- hosts: "{{ server | default('localhost') }}"
  vars:
    kafka_topic_name: 'test'
    kafka_zoo_servers:
      - master01:2181
      - master02:2181
      - master03:2181
  tasks:
    - name: delete_topic
      sudo: yes
      sudo_user: kafka
      shell: ./bin/kafka-topics.sh --delete --zookeeper {{ ",".join(kafka_zoo_servers) }}  --topic {{ kafka_topic_name }} chdir=/usr/local/kafka/default

    - name: list_topics
      sudo: yes
      sudo_user: kafka
      shell: ./bin/kafka-topics.sh --list --zookeeper {{ ",".join(kafka_zoo_servers) }} chdir=/usr/local/kafka/default
      register: topic_list

    - name: print_topic_list
      debug: msg="{{ topic_list.stdout }}"

